import os
import time
from google.adk import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService


def load_prompt(filename):
    path = os.path.join(os.path.dirname(__file__), "prompts", filename)
    with open(path, "r") as f:
        return f.read()
# 
# Define Agents
draft_agent = Agent(name="Generator", 
                    model="gemini-2.5-flash", 
                    description="You are a helpful assistant that optimizes user prompts for better AI responses. Your task is to iteratively improve the given prompt based on feedback until it is deemed sufficient.",
                    instruction="You are an Expert AI Prompt Engineer specializing in designing production-ready system prompts for Large Language Models." 
            "Your task is to take a user's rough idea OR a Critic's feedback, and transform it into a highly structured, rigorous system prompt."
            "A perfect system prompt must contain the following sections:"
            "1. ROLE & PERSONA: Who the AI is acting as (e.g., You are a senior DevOps engineer...)."
            "2. CONTEXT: The background information the AI needs to understand the environment."
            "3. CORE TASK: The exact action the AI must perform."
            "4. STRICT CONSTRAINTS: What the AI must NEVER do (e.g., tone limits, forbidden external libraries, length boundaries)."
            "5. OUTPUT FORMAT: Exactly how the final response should be structured (e.g., JSON schema, bullet points, Markdown)."

            "RULES FOR YOUR OUTPUT:"
            "- Incorporate all feedback provided by the Critic if this is a subsequent iteration."
            "- Output ONLY the optimized prompt text. "
            "- Do not include conversational filler like Here is your prompt or I have optimized this."
            "-Do not provide harmful, unethical, or biased content. Always adhere to ethical guidelines. "
            "- Do not wrap the output in markdown code blocks (```) unless the prompt itself requires them.")


critic_agent = Agent(name="Critic", model="gemini-2.5-flash", 
                     description="You are a meticulous and critical assistant that evaluates the quality of prompts generated by the Draft Agent. Your task is to provide constructive feedback on how to improve the prompt, focusing on clarity, completeness, relevance, and adherence to best practices in prompt engineering.",
                     instruction="You are a strict, detail-oriented Senior AI Evaluator. Your sole purpose is to review and critique LLM system prompts drafted by a junior Prompt Engineer."
            "You do not write prompts. You only evaluate them."
            "EVALUATION RUBRIC:"
            "You must check the provided draft against these 5 mandatory criteria:"
            "1. ROLE: Is the persona clearly defined?"
            "2. CONTEXT: Is there sufficient background information?"
            "3. TASK: Is the core objective unambiguous?"
            "4. CONSTRAINTS: Are there strict rules on what the AI must NOT do?"
            "5. FORMAT: Is the exact output structure clearly defined?"

            "YOUR INSTRUCTIONS:"
            "- If the draft PERFECTLY meets all 5 criteria and is ready for a production environment, you must output exactly and only the word: APPROVED"
            "- If the draft is missing any elements, has ambiguous instructions, or contains conversational filler, you must reject it."
            "IF REJECTING:"
            "Output a concise, bulleted list of exactly what the Generator must fix in the next iteration. "
            "Do NOT rewrite the prompt for them. "
            "Do NOT include conversational filler like Here is my feedback. "
            "Output ONLY the bulleted list of required fixes.")


assessment_agent = Agent(name="Assessor", model="gemini-2.5-flash", 
                         description="You are an impartial assistant that assesses the feedback from the Critic Agent and decides whether the current prompt draft is sufficient or needs further improvement. Your task is to determine if the prompt meets the necessary quality standards based on the Critic's feedback and to guide the loop accordingly.",
                         instruction= "You are an evaluator judging whether a critique indicates the draft is "
            "already of sufficient quality and needs no further revision.\n\n"
            "Respond in exactly this format (no other text):\n"
            "SUFFICIENT: YES or NO\n"
            "REASONING: <one short sentence>")

revise_agent = Agent(name="Reviser", model="gemini-2.5-flash", 
                     description="You are a diligent assistant responsible for revising the prompt draft based on the Critic's feedback. Your task is to take the current draft and the specific improvement suggestions from the Critic and produce a new, improved version of the prompt that addresses all the identified issues while adhering to best practices in prompt engineering.",
                     instruction="You are a Senior Prompt Refinement Specialist. Your exact task is to execute surgical revisions on LLM system prompts that have failed quality assurance."

            "YOUR INSTRUCTIONS:"
            "1. Analyze the Critic Feedback carefully. "
            "2. Apply the exact changes requested to the Current Draft."
            "3. Retain any sections of the Current Draft that were NOT criticized. Do not rewrite the entire prompt from scratch unnecessarily; only fix what is broken."
            "4. Ensure the final output still strictly adheres to the 5-part enterprise structure:"
            "- ROLE & PERSONA"
            "- CONTEXT"
            "- CORE TASK"
            "- STRICT CONSTRAINTS"
            "- OUTPUT FORMAT"

            "OUTPUT RULES:"
            "- Output ONLY the newly revised prompt text."
            "- Do NOT output any conversational filler (e.g., Here is the revised version, I have applied the feedback)."
            "- Do NOT include the critic's feedback in your output.")


def should_continue(session) -> bool:
    """
    In ADK, the condition function determines if the loop RUNS AGAIN.
    Returning False is the exact equivalent of routing to END.
    """
    last_assessment = session.get_last_message().text.lower()
    
    if "sufficient" in last_assessment:
        return False  # This triggers the LangGraph 'END'
    
    return True




async def execute_adk_optimization(user_input: str, max_iterations: int = 3):
    start_time = time.time()
    
    # Initialize session and runner
    session_service = InMemorySessionService()
    # Define constants for identifying the interaction context
    APP_NAME = "prompt_optimizer_app"
    USER_ID = "user_1"
    SESSION_ID = "session_001" # Using a fixed ID for simplicity

    # Create the specific session where the conversation will happen
    session = session_service.create_session(
        app_name=APP_NAME,
        user_id=USER_ID,
        session_id=SESSION_ID
    )
    print(f"Session created: App='{APP_NAME}', User='{USER_ID}', Session='{SESSION_ID}'")
    
    runner = Runner(agent=draft_agent, app_name=APP_NAME,   # Associates runs with our app
    session_service=session_service) # Uses our session manager)
    
    draft_response = runner.run(f"Initial Idea: {user_input}")
    current_draft = draft_response.text

    iterations = 0
    
    while iterations < max_iterations:
        
        # Draft -> Critic
        runner.agent = critic_agent
        critic_response = runner.run("Review the current draft in the session history and provide feedback.")
        
        if "APPROVED" in critic_response.text:
            break
            
        # Critic -> Assess
        runner.agent = assessment_agent
        assessment = runner.run("Evaluate the feedback. Is the draft sufficient? Output exactly YES or NO.")
        
        if "yes" in assessment.text.lower():
            break # This is your 'END'
            
        # 'needs_improvement' -> Revise
        runner.agent = revise_agent
        revise_response = runner.run("Apply the critic's feedback and generate a revised draft.")
    
        current_draft = revise_response.text
        
        # Increment to prevent infinite loops (acting as a safety edge)
        iterations += 1

    latency = round(time.time() - start_time, 2)
    
    return current_draft, latency