import os
import time
import asyncio
from google.adk import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from src.utils.config import calculate_prompt_response_tokens

# --- Session Management ---
# Key Concept: SessionService stores conversation history & state.
# InMemorySessionService is simple, non-persistent storage for this tutorial.
session_service = InMemorySessionService()

# Define constants for identifying the interaction context
APP_NAME = "propmt_optimizer_app"
USER_ID = "user_1"
SESSION_ID = "session_001" # Using a fixed ID for simplicity

# Define your custom configuration
generation_config = types.GenerateContentConfig(
    max_output_tokens=512,  # Limits the response to exactly 500 tokens
    temperature=0.2         # Optional: Controls creativity/determinism
)
# 
# Define Agents
draft_agent = Agent(name="Generator", 
                    model="gemini-2.5-flash-lite", 
                    description="You are a helpful assistant that optimizes user prompts for better AI responses. Your task is to iteratively improve the given prompt based on feedback until it is deemed sufficient.",
                    instruction="You are an Expert AI Prompt Engineer specializing in designing production-ready system prompts for Large Language Models." 
            "Your task is to take a user's rough idea OR a Critic's feedback, and transform it into a highly structured, rigorous system prompt."
            "A perfect system prompt must contain the following sections:"
            "1. ROLE & PERSONA: Who the AI is acting as (e.g., You are a senior DevOps engineer...)."
            "2. CONTEXT: The background information the AI needs to understand the environment."
            "3. CORE TASK: The exact action the AI must perform."
            "4. STRICT CONSTRAINTS: What the AI must NEVER do (e.g., tone limits, forbidden external libraries, length boundaries)."
            "5. OUTPUT FORMAT: Exactly how the final response should be structured (e.g., JSON schema, bullet points, Markdown)."

            "RULES FOR YOUR OUTPUT:"
            "- Incorporate all feedback provided by the Critic if this is a subsequent iteration."
            "- Output ONLY the optimized prompt text. "
            "- Do not include conversational filler like Here is your prompt or I have optimized this."
            "-Do not provide harmful, unethical, or biased content. Always adhere to ethical guidelines. "
            "- Do not wrap the output in markdown code blocks (```) unless the prompt itself requires them.",
            generate_content_config=generation_config)


critic_agent = Agent(name="Critic", model="gemini-2.5-flash-lite", 
                     description="You are a meticulous and critical assistant that evaluates the quality of prompts generated by the Draft Agent. Your task is to provide constructive feedback on how to improve the prompt, focusing on clarity, completeness, relevance, and adherence to best practices in prompt engineering.",
                     instruction="You are a strict, detail-oriented Senior AI Evaluator. Your sole purpose is to review and critique LLM system prompts drafted by a junior Prompt Engineer."
            "You do not write prompts. You only evaluate them."
            "EVALUATION RUBRIC:"
            "You must check the provided draft against these 5 mandatory criteria:"
            "1. ROLE: Is the persona clearly defined?"
            "2. CONTEXT: Is there sufficient background information?"
            "3. TASK: Is the core objective unambiguous?"
            "4. CONSTRAINTS: Are there strict rules on what the AI must NOT do?"
            "5. FORMAT: Is the exact output structure clearly defined?"

            "YOUR INSTRUCTIONS:"
            "- If the draft PERFECTLY meets all 5 criteria and is ready for a production environment, you must output exactly and only the word: APPROVED"
            "- If the draft is missing any elements, has ambiguous instructions, or contains conversational filler, you must reject it."
            "IF REJECTING:"
            "Output a concise, bulleted list of exactly what the Generator must fix in the next iteration. "
            "Do NOT rewrite the prompt for them. "
            "Do NOT include conversational filler like Here is my feedback. "
            "Output ONLY the bulleted list of required fixes.",
            generate_content_config=generation_config
            )


assessment_agent = Agent(name="Assessor", model="gemini-2.5-flash-lite", 
                         description="You are an impartial assistant that assesses the feedback from the Critic Agent and decides whether the current prompt draft is sufficient or needs further improvement. Your task is to determine if the prompt meets the necessary quality standards based on the Critic's feedback and to guide the loop accordingly.",
                         instruction= "You are an evaluator judging whether a critique indicates the draft is "
            "already of sufficient quality and needs no further revision.\n\n"
            "Respond in exactly this format (no other text):\n"
            "SUFFICIENT: YES or NO\n"
            "REASONING: <one short sentence>",
            generate_content_config=generation_config)

revise_agent = Agent(name="Reviser", model="gemini-2.5-flash-lite", 
                     description="You are a diligent assistant responsible for revising the prompt draft based on the Critic's feedback. Your task is to take the current draft and the specific improvement suggestions from the Critic and produce a new, improved version of the prompt that addresses all the identified issues while adhering to best practices in prompt engineering.",
                     instruction="You are a Senior Prompt Refinement Specialist. Your exact task is to execute surgical revisions on LLM system prompts that have failed quality assurance."

            "YOUR INSTRUCTIONS:"
            "1. Analyze the Critic Feedback carefully. "
            "2. Apply the exact changes requested to the Current Draft."
            "3. Retain any sections of the Current Draft that were NOT criticized. Do not rewrite the entire prompt from scratch unnecessarily; only fix what is broken."
            "4. Ensure the final output still strictly adheres to the 5-part enterprise structure:"
            "- ROLE & PERSONA"
            "- CONTEXT"
            "- CORE TASK"
            "- STRICT CONSTRAINTS"
            "- OUTPUT FORMAT"

            "OUTPUT RULES:"
            "- Output ONLY the newly revised prompt text."
            "- Do NOT output any conversational filler (e.g., Here is the revised version, I have applied the feedback)."
            "- Do NOT include the critic's feedback in your output.",
            generate_content_config=generation_config)


async def call_agent_async(query: str, runner, user_id, session_id) -> str:
    """Sends a query to the agent and prints the final response."""
    print(f"\n>>> User Query: {query}")

    # Prepare the user's message in ADK format
    content = types.Content(role='user', parts=[types.Part(text=query)])

    final_response_text = "Agent did not produce a final response." # Default

    # Key Concept: run_async executes the agent logic and yields Events.
    # We iterate through events to find the final answer.
    async for event in runner.run_async(user_id=user_id, session_id=session_id, new_message=content):
    
        # Key Concept: is_final_response() marks the concluding message for the turn.
        if event.is_final_response():
            if event.content and event.content.parts:
                # Assuming text response in the first part
                final_response_text = event.content.parts[0].text
            elif event.actions and event.actions.escalate: # Handle potential errors/escalations
                final_response_text = f"Agent escalated: {event.error_message or 'No specific message.'}"
            # Add more checks here if needed (e.g., specific error codes)
            break # Stop processing events once the final response is found

    return final_response_text

async def init_session(app_name:str,user_id:str,session_id:str) -> InMemorySessionService:
    
    # IF the session already exists, reuse it. This allows us to maintain conversation history across multiple calls to call_agent_async within the same optimization loop.
    if session_service.get_session(app_name=app_name, user_id=user_id, session_id=session_id):
        print(f"Session with ID '{session_id}' already exists. Reusing existing session.")
        return session_service.get_session(app_name=app_name, user_id=user_id, session_id=session_id)
    
    session =  session_service.create_session(
        app_name=app_name,
        user_id=user_id,
        session_id=session_id
    )
    print(f"Session created: App='{app_name}', User='{user_id}', Session='{session_id}'")
    return session


def clear_adk_session(session_id: str) -> bool:
    """Clear a session from the in-memory ADK session store."""
    try:
        session_service.delete_session(app_name=APP_NAME, user_id=USER_ID, session_id=session_id)
        return True
    except Exception:
        return False

async def execute_adk_optimization(user_input: str, max_iterations: int = 3, session_id: str = SESSION_ID):
    start_time = time.time()
    input_tokens = 0
    output_tokens = 0
    
    session = await init_session(APP_NAME, USER_ID, session_id)
    
    print(f"Session created: App='{APP_NAME}', User='{USER_ID}', Session='{session_id}'")
    
    runner = Runner(agent=draft_agent, app_name=APP_NAME,   # Associates runs with our app
    session_service=session_service)  # Use our session management
    
    draft_prompt = f"Optimize this: {user_input}."
    draft_response = await call_agent_async(draft_prompt,
                                            runner=runner, 
                                            user_id=USER_ID, 
                                            session_id=session_id)
    token_counts = calculate_prompt_response_tokens(draft_prompt, draft_response)
    input_tokens += token_counts["input_tokens"]
    output_tokens += token_counts["output_tokens"]
    current_draft = draft_response
    
    print(f"\nInitial Draft: {current_draft}")

    iterations = 0
    
    while iterations < max_iterations:
        # Draft -> Critic
        runner.agent = critic_agent
        critic_prompt = f"Critique this draft: {current_draft}"
        critic_response = await call_agent_async(critic_prompt,
                                                 runner=runner,
                                                    user_id=USER_ID,
                                                                     session_id=session_id)
        token_counts = calculate_prompt_response_tokens(critic_prompt, critic_response)
        input_tokens += token_counts["input_tokens"]
        output_tokens += token_counts["output_tokens"]
        
        print(f"\nCritic Feedback: {critic_response}")
        
        # Critic -> Assess
        runner.agent = assessment_agent
        assessment_prompt = f"Assess this critique: {critic_response}"
        assessment = await call_agent_async(assessment_prompt,
                                                 runner=runner,
                                                    user_id=USER_ID,
                                                                     session_id=session_id)
        token_counts = calculate_prompt_response_tokens(assessment_prompt, assessment)
        input_tokens += token_counts["input_tokens"]
        output_tokens += token_counts["output_tokens"]
        print(f"\nAssessment: {assessment}")
        
        assessment_upper = assessment.upper()
        if "SUFFICIENT: YES" in assessment_upper or "SUFFICIENT:YES" in assessment_upper:
            break
        
        # 'needs_improvement' -> Revise
        runner.agent = revise_agent
        revise_prompt = f"Revise the draft: {current_draft} based on this critique: {critic_response}"
        revise_response = await call_agent_async(revise_prompt,
                                                 runner=runner,
                                                    user_id=USER_ID,
                                                                     session_id=session_id)
        token_counts = calculate_prompt_response_tokens(revise_prompt, revise_response)
        input_tokens += token_counts["input_tokens"]
        output_tokens += token_counts["output_tokens"]
        print(f"\nRevised Draft: {revise_response}")
    
        current_draft = revise_response
        
        # Increment to prevent infinite loops (acting as a safety edge)
        iterations += 1
        print(f"--- End of iteration {iterations} ---")
        
    print(f"--- Examining Session Properties ---")
    print(f"ID (`id`):                {session.id}")
    print(f"Application Name (`app_name`): {session.app_name}")
    print(f"User ID (`user_id`):         {session.user_id}")
    print(f"State (`state`):           {session.state}") # Note: Only shows initial state here
    print(f"Events (`events`):         {session.events}") # Initially empty
    print(f"Last Update (`last_update_time`): {session.last_update_time:.2f}")
    print(f"---------------------------------")

    latency = round(time.time() - start_time, 2)

    print("--- Demo Metrics (ADK) ---")
    print(f"Input Tokens:  {input_tokens}")
    print(f"Output Tokens: {output_tokens}")
    print(f"Revision Count: {iterations}")
    print(f"Latency (s):    {latency}")
    print("--------------------")
    
    
    return current_draft, latency, input_tokens, output_tokens